/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as EspecialistasRouteImport } from './routes/especialistas'
import { Route as NosotrosRouteImport } from './routes/nosotros'
import { Route as EspecialistasIdRouteImport } from './routes/especialistas.$id'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const EspecialistasRoute = EspecialistasRouteImport.update({
  id: '/especialistas',
  path: '/especialistas',
  getParentRoute: () => rootRouteImport,
} as any)
const NosotrosRoute = NosotrosRouteImport.update({
  id: '/nosotros',
  path: '/nosotros',
  getParentRoute: () => rootRouteImport,
} as any)
const EspecialistasIdRoute = EspecialistasIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => EspecialistasRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/especialistas': typeof EspecialistasRouteWithChildren
  '/nosotros': typeof NosotrosRoute
  '/especialistas/$id': typeof EspecialistasIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/especialistas': typeof EspecialistasRouteWithChildren
  '/nosotros': typeof NosotrosRoute
  '/especialistas/$id': typeof EspecialistasIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/especialistas': typeof EspecialistasRouteWithChildren
  '/nosotros': typeof NosotrosRoute
  '/especialistas/$id': typeof EspecialistasIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/especialistas' | '/nosotros' | '/especialistas/$id'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/especialistas' | '/nosotros' | '/especialistas/$id'
  id: '__root__' | '/' | '/especialistas' | '/nosotros' | '/especialistas/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  EspecialistasRoute: typeof EspecialistasRouteWithChildren
  NosotrosRoute: typeof NosotrosRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/especialistas': {
      id: '/especialistas'
      path: '/especialistas'
      fullPath: '/especialistas'
      preLoaderRoute: typeof EspecialistasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/nosotros': {
      id: '/nosotros'
      path: '/nosotros'
      fullPath: '/nosotros'
      preLoaderRoute: typeof NosotrosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/especialistas/$id': {
      id: '/especialistas/$id'
      path: '/$id'
      fullPath: '/especialistas/$id'
      preLoaderRoute: typeof EspecialistasIdRouteImport
      parentRoute: typeof EspecialistasRoute
    }
  }
}

interface EspecialistasRouteChildren {
  EspecialistasIdRoute: typeof EspecialistasIdRoute
}

const EspecialistasRouteChildren: EspecialistasRouteChildren = {
  EspecialistasIdRoute: EspecialistasIdRoute,
}

const EspecialistasRouteWithChildren = EspecialistasRoute._addFileChildren(
  EspecialistasRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  EspecialistasRoute: EspecialistasRouteWithChildren,
  NosotrosRoute: NosotrosRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
